### ISSUE TITLE
Publish protectli_vp2420_v1.2.0

### ISSUE THREAD

**Issue by Lcchy** [protectli-root/build_coreboot#1]
As I am looking into modifying my coreboot install I noticed that this repo is missing some devices/branches.

Could you please push the branches for the build of `protectli_vp2420_v1.2.0` ?

Thank you very much.

**Comment by SergeyKonst3** [comment]
Hello Lcchy,

As we haven't updated to the latest, you can find an alternative method below.

You can find build instructions for [vp2420](https://docs.dasharo.com/unified/protectli/building-manual/#vp2420)

While the build instruction specify v1.1.0 you can replace the version number with v1.2.0 for example,  `git checkout protectli_vault_ehl_v1.2.0`

The exact [github for v1.2.0](https://github.com/Dasharo/coreboot/tree/protectli_vault_ehl_v1.2.0)

I hope this helps, if you have any questions please feel free to add it here.

**Comment by Lcchy** [comment]
Hi! Thanks a lot for your quick response! I had the suspicion that it was a version bump, thanks for confirming :)
